clc;clear all;
a = 0;
b = 0.8;
n0 = -2;
n1 = 10;
n = n0:n1;
x = 0.5.^(n).*exp((a+b*1i)*n);
figure(1);
subplot(2,1,1);
stem(n,real(x),'.');
axis([-4,10,min(real(x))-1,1.2*max(real(x))]);
title('复指数序列');
ylabel('实部');
grid;
subplot(2,1,2);
stem(n,imag(x),'.');
axis([-4,10,min(imag(x))-1,1.2*max(imag(x))]);
ylabel('虚部');
xlabel('n');
grid;